/**
 * Enhanced Portal Form Filler v2
 *
 * Uses semantic embedding-based matching with intelligent fallbacks.
 * Handles radio groups, checkboxes, and complex field types properly.
 */

import type { ScrapedForm, ScrapedField, UserProfile, FillResult } from '../types/index';
import { matchFieldsSmart } from '../agents/smart-matcher';

// Group radio buttons by name attribute
function groupRadioFields(fields: ScrapedField[]): Map<string, ScrapedField[]> {
  const groups = new Map<string, ScrapedField[]>();
  
  for (const field of fields) {
    if (field.type === 'radio' && field.name) {
      if (!groups.has(field.name)) {
        groups.set(field.name, []);
      }
      groups.get(field.name)!.push(field);
    }
  }
  
  return groups;
}

// Select best radio option based on value match
function selectRadioOption(
  group: ScrapedField[],
  targetValue: string
): ScrapedField | undefined {
  const normalized = targetValue.toLowerCase().trim();
  
  // Exact match
  for (const field of group) {
    if (field.value?.toLowerCase() === normalized) return field;
    if (field.label?.toLowerCase() === normalized) return field;
  }
  
  // Partial match
  for (const field of group) {
    if (
      field.value?.toLowerCase().includes(normalized) ||
      field.label?.toLowerCase().includes(normalized)
    ) {
      return field;
    }
  }
  
  // Default to first option if no match
  return group[0];
}

// CSS.escape polyfill for Node.js
function cssEscape(value: string): string {
  return value.replace(/([^a-zA-Z0-9_-])/g, '\\\\$1');
}

export async function fillFormEnhanced(
  url: string,
  form: ScrapedForm,
  profile: UserProfile,
  options: { submit?: boolean; headless?: boolean; timeout?: number } = {}
): Promise<FillResult> {
  const { chromium } = await import('playwright');

  const headless = options.headless !== false;
  const timeout = options.timeout || 30_000;

  const browser = await chromium.launch({ headless }).catch(() =>
    chromium.launch({ channel: 'chrome', headless })
  );
  
  const page = await browser.newPage();
  page.setDefaultTimeout(timeout);

  const fills: Record<string, string> = {};
  const skipped: Record<string, string> = {};
  let fieldsAttempted = 0;
  let fieldsFilled = 0;
  let fieldsFailed = 0;

  const startTime = Date.now();

  try {
    await page.goto(url, { waitUntil: 'networkidle', timeout });

    // 1. Get semantic matches
    console.log(`[filler] Matching ${form.fields.length} fields with smart matcher...`);
    const matches = await matchFieldsSmart(form.fields, profile);
    console.log(`[filler] Found ${matches.length} matches`);

    // 2. Handle radio button groups separately
    const radioGroups = groupRadioFields(form.fields);
    const handledRadios = new Set<string>();

    // 3. Fill matched fields
    for (const match of matches) {
      const { field, value, confidence, method } = match;
      
      // Skip if already handled as part of radio group
      if (field.type === 'radio' && field.name && handledRadios.has(field.name)) {
        continue;
      }

      fieldsAttempted++;

      try {
        // Build selector priority: name > id (only if not autogenerated)
        const isAutoId = field.id?.startsWith('field_');
        let selector: string | null = null;

        if (field.name) {
          selector = `[name="${field.name}"]`;
        } else if (field.id && !isAutoId) {
          selector = `#${cssEscape(field.id)}`;
        }

        if (!selector) {
          fieldsFailed++;
          skipped[field.id || field.name || 'unknown'] = 'no valid selector';
          continue;
        }

        // Wait for element to be available
        await page.waitForSelector(selector, { timeout: 5000, state: 'attached' }).catch(() => null);

        const element = await page.$(selector);
        if (!element) {
          fieldsFailed++;
          skipped[field.id || field.name || 'unknown'] = `element not found: ${selector}`;
          continue;
        }

        // Handle different field types
        if (field.type === 'radio' && field.name) {
          // Find best radio option in group
          const group = radioGroups.get(field.name);
          if (group) {
            const selected = selectRadioOption(group, value);
            if (selected) {
              const radioSelector = `[name="${selected.name}"][value="${selected.value || ''}"]`;
              
              await page.check(radioSelector);
              fills[field.name] = selected.value || selected.label || value;
              fieldsFilled++;
              handledRadios.add(field.name);
            }
          }
        } else if (field.type === 'checkbox') {
          const shouldCheck = ['true', '1', 'yes', 'on'].includes(value.toLowerCase());
          if (shouldCheck) {
            await page.check(selector);
            fills[field.id || field.name || 'unknown'] = value;
            fieldsFilled++;
          } else {
            await page.uncheck(selector);
            fills[field.id || field.name || 'unknown'] = 'false';
            fieldsFilled++;
          }
        } else if (field.type === 'select') {
          // Try label first, then value
          try {
            await page.selectOption(selector, { label: value });
            fills[field.id || field.name || 'unknown'] = value;
            fieldsFilled++;
          } catch {
            await page.selectOption(selector, { value });
            fills[field.id || field.name || 'unknown'] = value;
            fieldsFilled++;
          }
        } else if (field.type === 'textarea' || field.type === 'text' || field.type === 'email' || field.type === 'tel') {
          await page.fill(selector, value);
          fills[field.id || field.name || 'unknown'] = value;
          fieldsFilled++;
        } else {
          // Generic fill for other input types
          await page.fill(selector, value);
          fills[field.id || field.name || 'unknown'] = value;
          fieldsFilled++;
        }

        console.log(
          `[filler] ✓ ${field.label || field.name} = "${value}" (${method}, conf=${confidence.toFixed(2)})`
        );
      } catch (err) {
        fieldsFailed++;
        const errMsg = err instanceof Error ? err.message : 'unknown error';
        skipped[field.id || field.name || 'unknown'] = errMsg;
        console.error(`[filler] ✗ Failed to fill ${field.label || field.name}:`, errMsg);
      }
    }

    // 4. Take screenshot
    const screenshotBuffer = await page.screenshot({ fullPage: false });
    const screenshotBase64 = screenshotBuffer.toString('base64');

    // 5. Optional submit
    if (options.submit) {
      const submitBtn = await page.$('[type="submit"]');
      if (submitBtn) {
        await submitBtn.click();
        await page.waitForLoadState('networkidle').catch(() => {});
      }
    }

    const durationMs = Date.now() - startTime;

    return {
      fieldsAttempted,
      fieldsFilled,
      fieldsFailed,
      fills,
      skipped,
      screenshot: `data:image/png;base64,${screenshotBase64}`,
      success: fieldsFilled > 0 && fieldsFailed === 0,
      durationMs,
    };
  } catch (err) {
    const durationMs = Date.now() - startTime;
    const errMsg = err instanceof Error ? err.message : 'Unknown error';

    return {
      fieldsAttempted,
      fieldsFilled,
      fieldsFailed,
      fills,
      skipped,
      error: errMsg,
      success: false,
      durationMs,
    };
  } finally {
    await browser.close();
  }
}
